### ISSUE TITLE
【lame】audio encode decode

### ISSUE THREAD

**Issue by suliveevil** [holzschu/a-Shell-commands#1]
Would you please add lame for a-Shell？

>https://lame.sourceforge.io/
> LAME is a high quality MPEG Audio Layer III (MP3) encoder licensed under the LGPL.

**Comment by tydell** [comment]
I agree, ffmpeg.wasm compiled with Lame MP3 support would be something great.

**Comment by holzschu** [comment]
So, I tried compiling lame with webAssembly. It does compile but it does not run (it crashes, silently, between `main(arg, argv)` and `lame_main(gf, args, argv)`. 
@tydell, if I read you correctly, you don't want the lame binary, but the lame library, linked into ffmpeg for MP3 support?

**Comment by tydell** [comment]
@holzschu yes, i thought about library linked into ffmpeg for mp3 support

**Comment by TwentyH** [comment]
It also would like libmp3lame included in a-Shell, is there any progress on that please?

**Comment by shifujun** [comment]
`libmp3lame` will be very useful. Because iOS doesn't have the ability to export mp3 itself. Most of the apps available are not free.

**Comment by shifujun** [comment]
maybe https://github.com/ffmpegwasm/ffmpeg.wasm-core can be used. but I try run it with `wasm ffmpeg-core.wasm`, nothing output. maybe `wasm` have some special entry point?

**Comment by holzschu** [comment]
So, ffmpeg is now native in a-Shell, which makes porting LAME simpler. I've added it to the TODO list.
