### ISSUE TITLE
Enable key repeat on iOS / iPadOS for normal key  H, J, K and L

### ISSUE THREAD

**Issue by avvocati-e-mac** [holzschu/a-Shell-commands#10]
I would like to use H, J, K and L as the arrow key in Vim, but for those letter (differently that the arrow key) if you press for example K the keyboard type only one K and you have to re-press the K to go up a line.

I use an iPad Pro 3td generation 12.9 and a smart Folio Keyboard. I’m on the _public beta_ so it’s possibile is a bug.

I’ve abilitate key repeat in the accessibility panel of iOS / iPadOS. The arrow keys where affected (I decreased the time delay) but not the “normal” key.  

From what I read [online](https://apple.stackexchange.com/questions/92101/how-do-i-enable-key-repeat-on-ios#344393) is a problem of Apple but I heard that in the last iOS / iPadOS something was introduced for key press release (but I’m not a programmer).

**Comment by holzschu** [comment]
Hi, thanks for raising the issue. I had seen the "key press / release" novelty in iOS 15, but had not connected with the long-standing problem of key repeat in Vim (which is really annoying, I agree with you).

One problem here is that some languages use multiple-keys to enter character, and that interferes with auto-repeat. 

The settings "use caps-lock as escape" (in Settings) has the unexpected side effect to activate auto-repeat in Vim (and deactivate multi-char input). I could change the name, or make a separate settings for "Auto-repeat in Vim".
