### ISSUE TITLE
Are shell scripts supported?

### ISSUE THREAD

**Issue by atnbueno** [holzschu/a-Shell-commands#12]
I've tried with a simple `test.sh` file with a single command: `date`. After giving it 755 permissions, if I try to run it, it says "command not found" (I've tried running it as `./test.sh` and moving it to `~/Documents/bin`, which is in `$PATH`).

**Comment by atnbueno** [comment]
Sorry. Wrong repo.

**Comment by holzschu** [comment]
Hi, thanks for closing the issue. Yes, shell scripts themselves are not supported (yet). This is very hard, but I keep trying regularly. For now, you have Perl, Python and Lua scripts. Also, Shortcuts can run multiple commands in sequence, but that's not the same.
