### ISSUE TITLE
How to use admin commands?

### ISSUE THREAD

**Issue by naryfa** [holzschu/a-Shell-commands#14]
Any way to use sudo? Can it be compiled / installed? I can't even access /etc
  :(

**Comment by holzschu** [comment]
Hi,
the goal is to make an app that is compatible with the AppStore rules and restrictions. Making sudo (or any way to be super-user) would not be approved by Apple. The important files for a-Shell are in `$HOME` and `$APPDIR`, and you have access to them. 

/ is a funny bit: you can read /, but no directories under it, but some sub-directories (try /System/Library).

**Comment by naryfa** [comment]
Then maybe release these commands here, as installable, let users find and install them. You'd still be compliant with the app in the store. No?

**Comment by holzschu** [comment]
It's not the commands that are the problem, it's the ability to access root privilege. I can't create something in the App that lets users escalate privilege (it's also technically impossible, because Apple has several layers of protections).

**Comment by naryfa** [comment]
Sucks. OK, thanks for the info.
