### ISSUE TITLE
Run commands added to a-shell in extension rather than app

### ISSUE THREAD

**Issue by 0507spc** [holzschu/a-Shell-commands#28]
I have added commands to A-Shell but when I try to run in shortcuts I get the following:

"wasm: command not found"

I tried copying to bin, running with ./bin/command.wasm
~/Documents/bin

but nothing works, is this possible?

**Comment by holzschu** [comment]
Hi, 
That's an interesting question. For differents reasons, the shortcuts are running in a separate directory, `~shortcuts` or `$GROUP`. So the shortcut is not finding the command. You can copy it to `~shortcuts/bin` or even to `~shortcuts` if you call it with `wasm ~shortcuts/command` or `wasm command`.

**Comment by 0507spc** [comment]
I tried most of that, here is an example, I assume I am missing something:

![6C98EBBC-AE5F-4AE4-937A-995309EBECE7](https://user-images.githubusercontent.com/10354268/185786749-d9eac73c-dc23-4f8d-ba3c-46d9f6de8e12.png)

**Comment by holzschu** [comment]
Oh, sorry ! I forgot that webAssembly execution is done through Apple's own webAssembly engine (it's pretty efficient), so webAssembly is only available for shortcuts runnin in app, not for shortcuts running in extension.

**Comment by 0507spc** [comment]
Thanks for the time taken to reply, appreciate it. I wasn't sure if I was doing something wrong, I can change my flow, so no issues. Thanks again. :-)

**Comment by 0507spc** [comment]
Realised I posted in the wrong repo too. Sorry about that.
