### ISSUE TITLE
Cryptodome error on a-shell mini 1.9.5

### ISSUE THREAD

**Issue by adityasanghvi** [holzschu/a-Shell-commands#30]
Running a Python program that's dependent on Cryptodome module that throws an error _ModuleNotFoundError: No module named 'Crytodome'_

Tried "re-installing" pycryptodomex to see if it makes a difference with _pip install pycryptodomex_ and naturally the output is "Requirement already satisfied"

**Comment by holzschu** [comment]
I'm going to need a little more information. I tried with `yt-dlp`, which uses `pycryptodomex`, and it works. Do you have a command I could try, or a copy of the actual error message (with context) ?

**Comment by adityasanghvi** [comment]
I am using an audio decoder package that is dependent on Cryptodome. This is the error output while the command is run -

```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Data/Application/6EE547F0-0E61-4BC7-B650-29C07694002D/Documents/test-script.py", line 20, in <module>
    from sound.audio.decoders import AudioQuality, VorbisOnlyAudioQuality
  File "/var/mobile/Containers/Data/Application/6EE547F0-0E61-4BC7-B650-29C07694002D/Library/lib/python3.9/site-packages/sound/__init__.py", line 2, in <module>
    from sound.crypto import DiffieHellman
  File "/var/mobile/Containers/Data/Application/6EE547F0-0E61-4BC7-B650-29C07694002D/Library/lib/python3.9/site-packages/sound/crypto.py", line 2, in <module>
    from Cryptodome import Random
ModuleNotFoundError: No module named 'Cryptodome'
```

**Comment by holzschu** [comment]
You’re right, there’s a directory missing in a-Shell mini. It’ll be fixed in the next version. Thanks for raising this issue.

**Comment by adityasanghvi** [comment]
Great! Thanks for checking the root cause - and the non-mini version works fine as expected though.

**Comment by holzschu** [comment]
The TestFlight version of a-Shell mini should now work too: https://testflight.apple.com/join/REdHww5C
