### ISSUE TITLE
Problem using json output with ffprobe

### ISSUE THREAD

**Issue by dmedwards** [holzschu/a-Shell-commands#36]
Hi,

I'm using a-Shell mini 1.10.5 and ffprobe does not give the expected output with the -of json flag. What I get is JSON formatting but no keys or values.

Curiously, ffprobe gives the expected output when using the full a-Shell app version 1.10.4.

Thanks!

**Comment by dmedwards** [comment]
Upon further investigation, the -of json flag worked correctly in a-Shell mini when used by itself. The failure for me comes when I combine it with other flags like: 

ffprobe 'filename.mp4' -v error -show_format -show_streams -of json

**Comment by holzschu** [comment]
Thanks for the report. I found the issue. It will be fixed in version 1.10.6.

**Comment by dmedwards** [comment]
Thank you!
