### ISSUE TITLE
PKG repository down? 

### ISSUE THREAD

**Issue by tsadik** [holzschu/a-Shell-commands#49]
Hey there,

Is it just me or is the entire pkg listing just gone? 
Maybe it’s just been moved?

If anyone know’s of some alternatives that would be awesome.

**Comment by holzschu** [comment]
Can you be more explicit? (provide a screenshot, or at least an error message?) I don't see any abnormal behaviour.

**Comment by tsadik** [comment]
Terribly sorry. Looks like I had some local network issues?
